server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy /api/* -> jsonplaceholder (reemplaza el proxy de Vite en produccion)
    location /api/ {
        proxy_pass         https://jsonplaceholder.typicode.com/;
        proxy_ssl_server_name on;
        proxy_set_header   Host jsonplaceholder.typicode.com;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_hide_header  Access-Control-Allow-Origin;
        add_header         Access-Control-Allow-Origin *;
    }

    # Archivos estaticos con cache agresivo (hashed filenames)
    location ~* \.(js|css|woff2?|ttf|otf|eot|svg|png|jpg|jpeg|gif|ico|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback: todas las rutas sirven index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
